spring:
  ai:
    openai:
      chat:
        base-url: "https://ai-api.pincode-infra.ru"
        options:
          model: "openai/gpt-oss-120b"
          temperature: 1.0
      api-key: 123
  application:
    name: agent
  datasource:
    username: agent
    password: agent
    url: jdbc:postgresql://localhost:5432/agent
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
debug: true
